/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface CexAmlAuditTrailInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CEX_BACKEND"
      | "eventId"
      | "logDepositTrace"
      | "logResolution"
      | "logSuspicious"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AmlResolution"
      | "DepositTrace"
      | "SuspiciousActivity"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CEX_BACKEND",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "eventId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "logDepositTrace",
    values: [BytesLike, BytesLike, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "logResolution",
    values: [BytesLike, BytesLike, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "logSuspicious",
    values: [BytesLike, BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "CEX_BACKEND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "eventId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "logDepositTrace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logSuspicious",
    data: BytesLike
  ): Result;
}

export namespace AmlResolutionEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    userId: BytesLike,
    internalTxId: BytesLike,
    action: string,
    strFiled: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    eventId: bigint,
    userId: string,
    internalTxId: string,
    action: string,
    strFiled: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    eventId: bigint;
    userId: string;
    internalTxId: string;
    action: string;
    strFiled: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositTraceEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    userId: BytesLike,
    originalDepositTxHash: BytesLike,
    chainId: BigNumberish,
    sender: AddressLike,
    blockNumber: BigNumberish
  ];
  export type OutputTuple = [
    eventId: bigint,
    userId: string,
    originalDepositTxHash: string,
    chainId: bigint,
    sender: string,
    blockNumber: bigint
  ];
  export interface OutputObject {
    eventId: bigint;
    userId: string;
    originalDepositTxHash: string;
    chainId: bigint;
    sender: string;
    blockNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SuspiciousActivityEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    userId: BytesLike,
    internalTxId: BytesLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    eventId: bigint,
    userId: string,
    internalTxId: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    eventId: bigint;
    userId: string;
    internalTxId: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CexAmlAuditTrail extends BaseContract {
  connect(runner?: ContractRunner | null): CexAmlAuditTrail;
  waitForDeployment(): Promise<this>;

  interface: CexAmlAuditTrailInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CEX_BACKEND: TypedContractMethod<[], [string], "view">;

  eventId: TypedContractMethod<[], [bigint], "view">;

  logDepositTrace: TypedContractMethod<
    [
      userId: BytesLike,
      depositTxHash: BytesLike,
      chainId: BigNumberish,
      sender: AddressLike,
      blockNum: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  logResolution: TypedContractMethod<
    [
      userId: BytesLike,
      internalTxId: BytesLike,
      action: string,
      strFiled: boolean
    ],
    [void],
    "nonpayable"
  >;

  logSuspicious: TypedContractMethod<
    [userId: BytesLike, internalTxId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CEX_BACKEND"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eventId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "logDepositTrace"
  ): TypedContractMethod<
    [
      userId: BytesLike,
      depositTxHash: BytesLike,
      chainId: BigNumberish,
      sender: AddressLike,
      blockNum: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logResolution"
  ): TypedContractMethod<
    [
      userId: BytesLike,
      internalTxId: BytesLike,
      action: string,
      strFiled: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logSuspicious"
  ): TypedContractMethod<
    [userId: BytesLike, internalTxId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AmlResolution"
  ): TypedContractEvent<
    AmlResolutionEvent.InputTuple,
    AmlResolutionEvent.OutputTuple,
    AmlResolutionEvent.OutputObject
  >;
  getEvent(
    key: "DepositTrace"
  ): TypedContractEvent<
    DepositTraceEvent.InputTuple,
    DepositTraceEvent.OutputTuple,
    DepositTraceEvent.OutputObject
  >;
  getEvent(
    key: "SuspiciousActivity"
  ): TypedContractEvent<
    SuspiciousActivityEvent.InputTuple,
    SuspiciousActivityEvent.OutputTuple,
    SuspiciousActivityEvent.OutputObject
  >;

  filters: {
    "AmlResolution(uint256,bytes32,bytes32,string,bool,uint256)": TypedContractEvent<
      AmlResolutionEvent.InputTuple,
      AmlResolutionEvent.OutputTuple,
      AmlResolutionEvent.OutputObject
    >;
    AmlResolution: TypedContractEvent<
      AmlResolutionEvent.InputTuple,
      AmlResolutionEvent.OutputTuple,
      AmlResolutionEvent.OutputObject
    >;

    "DepositTrace(uint256,bytes32,bytes32,uint16,address,uint256)": TypedContractEvent<
      DepositTraceEvent.InputTuple,
      DepositTraceEvent.OutputTuple,
      DepositTraceEvent.OutputObject
    >;
    DepositTrace: TypedContractEvent<
      DepositTraceEvent.InputTuple,
      DepositTraceEvent.OutputTuple,
      DepositTraceEvent.OutputObject
    >;

    "SuspiciousActivity(uint256,bytes32,bytes32,string,uint256)": TypedContractEvent<
      SuspiciousActivityEvent.InputTuple,
      SuspiciousActivityEvent.OutputTuple,
      SuspiciousActivityEvent.OutputObject
    >;
    SuspiciousActivity: TypedContractEvent<
      SuspiciousActivityEvent.InputTuple,
      SuspiciousActivityEvent.OutputTuple,
      SuspiciousActivityEvent.OutputObject
    >;
  };
}
