/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace StablecoinMonitor {
  export type ComplianceCaseStruct = {
    status: BigNumberish;
    verdict: BigNumberish;
    riskScore: BigNumberish;
    sanctionsHit: boolean;
    notes: string;
    requestedAt: BigNumberish;
    resolvedAt: BigNumberish;
  };

  export type ComplianceCaseStructOutput = [
    status: bigint,
    verdict: bigint,
    riskScore: bigint,
    sanctionsHit: boolean,
    notes: string,
    requestedAt: bigint,
    resolvedAt: bigint
  ] & {
    status: bigint;
    verdict: bigint;
    riskScore: bigint;
    sanctionsHit: boolean;
    notes: string;
    requestedAt: bigint;
    resolvedAt: bigint;
  };

  export type TransferReportStruct = {
    asset: AddressLike;
    actor: AddressLike;
    counterparty: AddressLike;
    amount: BigNumberish;
    txHash: BytesLike;
    memo: string;
    reportedAt: BigNumberish;
  };

  export type TransferReportStructOutput = [
    asset: string,
    actor: string,
    counterparty: string,
    amount: bigint,
    txHash: string,
    memo: string,
    reportedAt: bigint
  ] & {
    asset: string;
    actor: string;
    counterparty: string;
    amount: bigint;
    txHash: string;
    memo: string;
    reportedAt: bigint;
  };
}

export interface StablecoinMonitorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ANALYST_ROLE"
      | "AUDITOR_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "POLICY_ROLE"
      | "getComplianceCase"
      | "getRoleAdmin"
      | "getTransfer"
      | "grantRole"
      | "hasRole"
      | "nextTransferId"
      | "renounceRole"
      | "reportTransfer"
      | "requestComplianceCheck"
      | "revokeRole"
      | "submitComplianceResult"
      | "supportsInterface"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ComplianceRequested"
      | "ComplianceResolved"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TransferReported"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ANALYST_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "AUDITOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "POLICY_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getComplianceCase",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransfer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextTransferId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reportTransfer",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BytesLike,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "requestComplianceCheck",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitComplianceResult",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ANALYST_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "AUDITOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "POLICY_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getComplianceCase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextTransferId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestComplianceCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitComplianceResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export namespace ComplianceRequestedEvent {
  export type InputTuple = [transferId: BigNumberish, requestedBy: AddressLike];
  export type OutputTuple = [transferId: bigint, requestedBy: string];
  export interface OutputObject {
    transferId: bigint;
    requestedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplianceResolvedEvent {
  export type InputTuple = [
    transferId: BigNumberish,
    policyAdmin: AddressLike,
    verdict: BigNumberish,
    riskScore: BigNumberish,
    sanctionsHit: boolean,
    notes: string
  ];
  export type OutputTuple = [
    transferId: bigint,
    policyAdmin: string,
    verdict: bigint,
    riskScore: bigint,
    sanctionsHit: boolean,
    notes: string
  ];
  export interface OutputObject {
    transferId: bigint;
    policyAdmin: string;
    verdict: bigint;
    riskScore: bigint;
    sanctionsHit: boolean;
    notes: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferReportedEvent {
  export type InputTuple = [
    transferId: BigNumberish,
    asset: AddressLike,
    actor: AddressLike,
    counterparty: AddressLike,
    amount: BigNumberish,
    txHash: BytesLike,
    memo: string
  ];
  export type OutputTuple = [
    transferId: bigint,
    asset: string,
    actor: string,
    counterparty: string,
    amount: bigint,
    txHash: string,
    memo: string
  ];
  export interface OutputObject {
    transferId: bigint;
    asset: string;
    actor: string;
    counterparty: string;
    amount: bigint;
    txHash: string;
    memo: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StablecoinMonitor extends BaseContract {
  connect(runner?: ContractRunner | null): StablecoinMonitor;
  waitForDeployment(): Promise<this>;

  interface: StablecoinMonitorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ANALYST_ROLE: TypedContractMethod<[], [string], "view">;

  AUDITOR_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  POLICY_ROLE: TypedContractMethod<[], [string], "view">;

  getComplianceCase: TypedContractMethod<
    [transferId: BigNumberish],
    [StablecoinMonitor.ComplianceCaseStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTransfer: TypedContractMethod<
    [transferId: BigNumberish],
    [StablecoinMonitor.TransferReportStructOutput],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  nextTransferId: TypedContractMethod<[], [bigint], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  reportTransfer: TypedContractMethod<
    [
      asset: AddressLike,
      actor: AddressLike,
      counterparty: AddressLike,
      amount: BigNumberish,
      txHash: BytesLike,
      memo: string
    ],
    [bigint],
    "nonpayable"
  >;

  requestComplianceCheck: TypedContractMethod<
    [transferId: BigNumberish],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  submitComplianceResult: TypedContractMethod<
    [
      transferId: BigNumberish,
      verdict: BigNumberish,
      riskScore: BigNumberish,
      sanctionsHit: boolean,
      notes: string
    ],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ANALYST_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "AUDITOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "POLICY_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getComplianceCase"
  ): TypedContractMethod<
    [transferId: BigNumberish],
    [StablecoinMonitor.ComplianceCaseStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTransfer"
  ): TypedContractMethod<
    [transferId: BigNumberish],
    [StablecoinMonitor.TransferReportStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextTransferId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reportTransfer"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      actor: AddressLike,
      counterparty: AddressLike,
      amount: BigNumberish,
      txHash: BytesLike,
      memo: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestComplianceCheck"
  ): TypedContractMethod<[transferId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitComplianceResult"
  ): TypedContractMethod<
    [
      transferId: BigNumberish,
      verdict: BigNumberish,
      riskScore: BigNumberish,
      sanctionsHit: boolean,
      notes: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  getEvent(
    key: "ComplianceRequested"
  ): TypedContractEvent<
    ComplianceRequestedEvent.InputTuple,
    ComplianceRequestedEvent.OutputTuple,
    ComplianceRequestedEvent.OutputObject
  >;
  getEvent(
    key: "ComplianceResolved"
  ): TypedContractEvent<
    ComplianceResolvedEvent.InputTuple,
    ComplianceResolvedEvent.OutputTuple,
    ComplianceResolvedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TransferReported"
  ): TypedContractEvent<
    TransferReportedEvent.InputTuple,
    TransferReportedEvent.OutputTuple,
    TransferReportedEvent.OutputObject
  >;

  filters: {
    "ComplianceRequested(uint256,address)": TypedContractEvent<
      ComplianceRequestedEvent.InputTuple,
      ComplianceRequestedEvent.OutputTuple,
      ComplianceRequestedEvent.OutputObject
    >;
    ComplianceRequested: TypedContractEvent<
      ComplianceRequestedEvent.InputTuple,
      ComplianceRequestedEvent.OutputTuple,
      ComplianceRequestedEvent.OutputObject
    >;

    "ComplianceResolved(uint256,address,uint8,uint8,bool,string)": TypedContractEvent<
      ComplianceResolvedEvent.InputTuple,
      ComplianceResolvedEvent.OutputTuple,
      ComplianceResolvedEvent.OutputObject
    >;
    ComplianceResolved: TypedContractEvent<
      ComplianceResolvedEvent.InputTuple,
      ComplianceResolvedEvent.OutputTuple,
      ComplianceResolvedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TransferReported(uint256,address,address,address,uint256,bytes32,string)": TypedContractEvent<
      TransferReportedEvent.InputTuple,
      TransferReportedEvent.OutputTuple,
      TransferReportedEvent.OutputObject
    >;
    TransferReported: TypedContractEvent<
      TransferReportedEvent.InputTuple,
      TransferReportedEvent.OutputTuple,
      TransferReportedEvent.OutputObject
    >;
  };
}
